services:
  giftbox-php:
    build:
      context: .
      dockerfile: Dockerfile.gift
    ports:
      - "8082:80"
    volumes:
      - ./gift.appli/public:/var/www/html
      - ./gift.appli/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - giftbox.net
    depends_on:
      - giftbox-db

  giftbox-db:
    image: bitnami/mariadb:11.4.6-debian-12-r0
    depends_on:
      - giftbox-db
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_password}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - "3307:3306"
    networks:
      - giftbox.net

  adminer:
    image: adminer
    ports:
      - "8083:8080"
    networks:
      - giftbox.net

  phpmyadmin:
    image: phpmyadmin:5.2.2
    depends_on:
      - giftbox-db
    environment:
      PMA_HOST: giftbox-db           # Se connecte au service MariaDB
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      # Optionnel : PMA_ABSOLUTE_URI, UPLOAD_LIMIT, etc.
    ports:
      - "8084:80"
    networks:
      - giftbox.net

networks:
  giftbox.net:
    driver: bridge
